[project]
name = "rag-system"
version = "0.1.0"
description = "A Rag system"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.2.7",
    "langchain-openai>=1.1.7",
    "mypy>=1.19.1",
    "pymupdf4llm>=0.2.9",
    "ruff>=0.14.14",
]
[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]  # Enable standard errors, formatting errors, and Import sorting

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
